package app.model;

import com.fasterxml.jackson.core.JsonProcessingException;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class SelectedFiltersTest {
    private static final String KEY_1 = "KEY_1";
    private static final String VALUE_1 = "VALUE_1";

    private static final String KEY_2 = "KEY_2";
    private static final String VALUE_2 = "VALUE_2";

    @Test
    void sanityTest() throws JsonProcessingException {
        //given
        Map<String, String> filters = new HashMap<>() {{
            put(KEY_1, VALUE_1);
            put(KEY_2, VALUE_2);
        }};
        SelectedFilters selectedFilters = new SelectedFilters(filters);

        //when
        String tag = selectedFilters.getTag();
        Map<String, String> actualFilters = selectedFilters.getFilters();
        String queryString = selectedFilters.getQueryString();

        //then
        assertEquals("__#AUTOGENERATED__" + filters.toString(), tag);
        assertEquals(filters, actualFilters);
        assertTrue(queryString.contains(KEY_1 + "=\"" + VALUE_1 + "\""));
        assertTrue(queryString.contains(KEY_2 + "=\"" + VALUE_2 + "\""));
    }
}
