package app.model;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class SelectedQueryDeserializerTest {
    private static final String TAG = "TAG";
    private static final String QUERY_STING = "QUERY_STRING";

    private static final String KEY = "KEY";
    private static final String VALUE = "VALUE";

    @Test
    void deserializeSimpleQueriesTest() throws JsonProcessingException {
        //given
        String simpleQueriesJson = "{\"filters\":{\"" + KEY + "\":\"" + VALUE + "\"}}";

        //when
        SelectedQuery selectedQuery = new ObjectMapper().readValue(simpleQueriesJson, SelectedQuery.class);

        //then
        assertEquals("__#AUTOGENERATED__{" + KEY + "=" + VALUE + "}", selectedQuery.getTag());
        assertEquals("{" + KEY + "=\"" + VALUE + "\"}", selectedQuery.getQueryString());
    }

    @Test
    void deserializeCustomQueryTest() throws JsonProcessingException {
        //given
        String customQueryJson = "{\"tag\":\"" + TAG + "\",\"queryString\":\"" + QUERY_STING + "\"}";

        //when
        SelectedQuery selectedQuery = new ObjectMapper().readValue(customQueryJson, SelectedQuery.class);

        //then
        assertEquals(TAG, selectedQuery.getTag());
        assertEquals(QUERY_STING, selectedQuery.getQueryString());
    }
}
