package app.model;

import app.services.QueryBuilderService;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Map;

public class SelectedFilters implements SelectedQuery {

    private final Map<String, String> filters;

    @JsonIgnore
    private final String query;

    public SelectedFilters(Map<String, String> filters) {
        this.filters = filters;
        this.query = QueryBuilderService.INSTANCE.filtersToQuery(filters);
    }

    @Override
    public String getTag() {
        // TODO temporary
        return "__#AUTOGENERATED__" + filters.toString();
    }

    @Override
    public String getQueryString() {
        return query;
    }

}
